name: cycads_env
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - jinja2~=3.1.3
 - matplotlib~=3.8.3
 - minimap2~=2.17
 - numpy~=1.26.4
 - pandas~=2.2.1
 - pyfastx~=2.1.0
 - pysam~=0.22.0
 - python ~= 3.8
 - samtools~=1.11
 - scipy~=1.12.0
 - seaborn~=0.13.2


          